### ISSUE TITLE
Bug in PUT template

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Link#49]
I called 
`http://api-dev.freme-project.eu/current/e-link/templates/77?token=a2baa132-da71-4cb9-b87a-e460bc67b168&informat=json&outformat=json` with body
```
 {
 "query":"a SPARQL CONSTRUCT query",
 "endpoint":"http://abc.de",
 "label":"THE title of the template",
 "description":"a description of the template"
 } 
```
The changes are saved but the return value is
```
{
    "exception": "eu.freme.broker.exception.InternalServerErrorException",
    "path": "/e-link/templates/77",
    "message": "Unknown problem. Please contact us.",
    "error": "Internal Server Error",
    "status": 500,
    "timestamp": 1444312793337
}
```

Some parts of the broker log:

```
ERROR   2015-10-08 15:59:00,820 [http-nio-8084-exec-4] eu.freme.broker.eservices.BaseRestController  - Request: http://rv1443.1blu.de:8084/e-link/templates/77 raised
eu.freme.broker.exception.InternalServerErrorException: Unknown problem. Please contact us.
        at eu.freme.broker.eservices.ELink.updateTemplateById(ELink.java:396)
```

```
ERROR   2015-10-08 15:58:16,276 [http-nio-8084-exec-9] eu.freme.broker.eservices.BaseRestController  - unsupported format: JSON
java.lang.RuntimeException: unsupported format: JSON
        at eu.freme.common.conversion.rdf.JenaRDFConversionService.serializeRDF(JenaRDFConversionService.java:104)
        at eu.freme.broker.eservices.ELink.updateTemplateById(ELink.java:372)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

**Comment by ArneBinder** [comment]
fixed.
